config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get '/crypto', to: 'home#crypto'
  get '/resul', to: 'home#resul'
  get '/movie', to: 'home#movie'


  get '/search', to: 'movies#search'

  get '/pequenotest', to: 'application#pequenotest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :warning

  def pequenotest
    render html: SayHello.new.perform
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def crypto
    if Crypto.first == nil 
            StartScrap.new.perform
    end
  end

  def movie

  end

  def resul
    @crypto = Crypto.all
    @a = @crypto.find_by crypto_name: params[:crypto_name].downcase
    if @a

    else

      redirect_to crypto_path ,  warning: "Error"
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def initialize
    Tmdb::Api.key(Rails.application.credentials.dig(:T_KEY))
  end

  def search

    count = params[:title]

    if count == ""
      render html: "no existe"
    else
      @parp = Tmdb::Movie.find(count)
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/crypto.html.erb
<%= warning %>

<div class="card text-center">
  <div class="card-body">
      <%= form_tag("/resul", method: "get") do %>
        <div class="form-group">
          <h1><%= label_tag(:title, "Nom du crypto") %></h1>
        </div>
        <div class="form-group">
          <%= text_field_tag(:crypto_name) %>
        </div>
      <div class="form-group">
        <%= submit_tag("Chercher") %>
      </div>
      <% end %>
  </div>
</div>

app/views/home/movie.html.erb
<div class="card text-center">
  <div class="card-body">
    <%= form_tag("/search", method: "get") do %>
      <div class="form-group">
        <h1><%= label_tag(:title, "Nom du film") %></h1>
      </div>
      <div class="form-group">
        <%= text_field_tag(:title) %>
      </div>
      <div class="form-group">
        <%= submit_tag("Chercher") %>
      </div>
    <% end %>
  </div>
</div>

app/views/home/resul.html.erb
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="card-body">
        <a class="nav-link active" href="<%= crypto_path %>">Chercher un autre</a>
      </li>
    </ul>
  </div>

  <div class="card-body">
    <h5 class="card-title"><%= @a.crypto_name %></h5>
    <p class="card-text"><%= @a.cours %></p>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://mdbootstrap.com/previews/docs/latest/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://mdbootstrap.com/previews/docs/latest/css/mdb.min.css" rel="stylesheet">
    <link href="style.css" rel="stylesheet">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark default-color-dark">
    <a class="navbar-brand" href="/">SaphYr</a>
    <div>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= crypto_path %>">Crypto</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= movie_path %>">Film</a>
        </li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/movies/search.html.erb
<% if !@parp %>

<% else %>
  <% i=0 %>
  <% @parp.each do |movie| %>
    <%= image_tag "https://image.tmdb.org/t/p/w185_and_h278_bestv2#{movie.poster_path}", class: "card-img-top"%><br>
    <%= movie.title %><br>
    <%= movie.release_date %><br>
    <% i+=1 %>
    <% break if i == 20 %>
  <% end %>
<% end %>